[build]
builder = "NIXPACKS"
buildCommand = "NODE_ENV=development npm ci && npx prisma generate && NODE_ENV=production npm run build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
PORT = "3000"
